version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reportgenerator
    # Ports removed to only allow access via Nginx
    # ports:
    #   - "3000:3000" 
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/reportgenerator
    depends_on:
      - mongodb
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: reportgenerator-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro # Keep for initial compatible startup if needed, though we will move to letsencrypt
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    container_name: reportgenerator-certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot

  # MongoDB Service
  mongodb:
    image: mongo:7
    container_name: reportgenerator-db
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
    # profiles removed to start by default

volumes:
  mongodb_data:
